### ISSUE TITLE
Implement invertible kmer hash function

### ISSUE THREAD

**Issue by rmnorris** [rmnorris/pandora#2]
Want to avoid poly-A kmers always achieving the minimizing value - distribute minimizing kmers more evenly across the set of all kmers

**Comment by iqbal-lab** [comment]
Heng mentions how he avoids this, I recall, @rmnorris

**Comment by rmnorris** [comment]
He does. This is note to self to do it

**Comment by iqbal-lab** [comment]
Ah comprendo
