### ISSUE TITLE
Memory leaks

### ISSUE THREAD

**Issue by rmnorris** [rmnorris/pandora#4]
Check the output from command:
/home/zam/bin/bin/valgrind --leak-check=yes --track-origins=yes -v build/pandora test/test_cases/prg4567.fa test/test_cases/read0.fa wow &> build/pandora_valgrind_output.txt

START: Wed Oct 26 20:23:44 2016

Building Index from PRG file
--39147-- REDIR: 0x3a146bd1d0 (operator new[](unsigned long)) redirected to 0x4a0794a (operator new[](unsigned long))
--39147-- REDIR: 0x3a11e83350 (memchr) redirected to 0x4a09890 (memchr)
--39147-- REDIR: 0x3a146bb2f0 (operator delete(void_)) redirected to 0x4a072ec (operator delete(void_))
--39147-- REDIR: 0x3a11e833d0 (bcmp) redirected to 0x480260a (_vgnU_ifunc_wrapper)
--39147-- REDIR: 0x3a11f3e6d0 (__memcmp_sse4_1) redirected to 0x4a0a8c0 (bcmp)
--39147-- REDIR: 0x3a11e83800 (memmove) redirected to 0x4a0ad40 (memmove)
--39147-- REDIR: 0x3a146bb330 (operator delete[](void*)) redirected to 0x4a06f68 (operator delete[](void*))
Reading Read file
Finished building PanGraph from reads
Writing PanGraph to file
FINISH: Wed Oct 26 20:23:46 2016

==39147== 
==39147== HEAP SUMMARY:
==39147==     in use at exit: 504 bytes in 16 blocks
==39147==   total heap usage: 1,934 allocs, 1,918 frees, 454,491 bytes allocated
==39147== 
==39147== Searching for pointers to 16 not-freed blocks
==39147== Checked 207,608 bytes
==39147== 
==39147== 504 (48 direct, 456 indirect) bytes in 1 blocks are definitely lost in loss record 9 of 9
==39147==    at 0x4A07EB6: operator new(unsigned long) (vg_replace_malloc.c:287)
==39147==    by 0x44790C: main (in /data2/users/rachel/projects/pandora/build/pandora)
==39147== 
==39147== LEAK SUMMARY:
==39147==    definitely lost: 48 bytes in 1 blocks
==39147==    indirectly lost: 456 bytes in 15 blocks
==39147==      possibly lost: 0 bytes in 0 blocks
==39147==    still reachable: 0 bytes in 0 blocks
==39147==         suppressed: 0 bytes in 0 blocks
==39147== 
==39147== ERROR SUMMARY: 3 errors from 3 contexts (suppressed: 4 from 4)
==39147== 
==39147== 1 errors in context 1 of 3:
==39147== Conditional jump or move depends on uninitialised value(s)
==39147==    at 0x3A11A1754B: index (in /lib64/ld-2.12.so)
==39147==    by 0x3A11A06237: expand_dynamic_string_token (in /lib64/ld-2.12.so)
==39147==    by 0x3A11A082F1: _dl_map_object (in /lib64/ld-2.12.so)
==39147==    by 0x3A11A016DD: map_doit (in /lib64/ld-2.12.so)
==39147==    by 0x3A11A0E265: _dl_catch_error (in /lib64/ld-2.12.so)
==39147==    by 0x3A11A015F6: do_preload (in /lib64/ld-2.12.so)
==39147==    by 0x3A11A0480E: dl_main (in /lib64/ld-2.12.so)
==39147==    by 0x3A11A15B4D: _dl_sysdep_start (in /lib64/ld-2.12.so)
==39147==    by 0x3A11A014A3: _dl_start (in /lib64/ld-2.12.so)
==39147==    by 0x3A11A00B07: ??? (in /lib64/ld-2.12.so)
==39147==    by 0x3: ???
==39147==    by 0xFFEFFF912: ???
==39147==  Uninitialised value was created by a stack allocation
==39147==    at 0x3A11A032A1: dl_main (in /lib64/ld-2.12.so)
==39147== 
==39147== 
==39147== 1 errors in context 2 of 3:
==39147== Conditional jump or move depends on uninitialised value(s)
==39147==    at 0x3A11A17546: index (in /lib64/ld-2.12.so)
==39147==    by 0x3A11A06237: expand_dynamic_string_token (in /lib64/ld-2.12.so)
==39147==    by 0x3A11A082F1: _dl_map_object (in /lib64/ld-2.12.so)
==39147==    by 0x3A11A016DD: map_doit (in /lib64/ld-2.12.so)
==39147==    by 0x3A11A0E265: _dl_catch_error (in /lib64/ld-2.12.so)
==39147==    by 0x3A11A015F6: do_preload (in /lib64/ld-2.12.so)
==39147==    by 0x3A11A0480E: dl_main (in /lib64/ld-2.12.so)
==39147==    by 0x3A11A15B4D: _dl_sysdep_start (in /lib64/ld-2.12.so)
==39147==    by 0x3A11A014A3: _dl_start (in /lib64/ld-2.12.so)
==39147==    by 0x3A11A00B07: ??? (in /lib64/ld-2.12.so)
==39147==    by 0x3: ???
==39147==    by 0xFFEFFF912: ???
==39147==  Uninitialised value was created by a stack allocation
==39147==    at 0x3A11A032A1: dl_main (in /lib64/ld-2.12.so)
==39147== 
--39147-- 
--39147-- used_suppression:      4 U1004-ARM-_dl_relocate_object
==39147== 
==39147== ERROR SUMMARY: 3 errors from 3 contexts (suppressed: 4 from 4)

**Comment by iqbal-lab** [comment]
If you compile for debug with -O0 -g then valgrind is able to tell you precise functions and lines
