### ISSUE TITLE
Speed up update_covgs

### ISSUE THREAD

**Issue by rmnorris** [rmnorris/pandora#8]
Currently takes about 10 mins for a single nanopore read, and 1 PRG, everything else takes seconds.

**Comment by iqbal-lab** [comment]
ping @rmnorris

**Comment by rmnorris** [comment]
Seems to have fixed with other bug fixes. Alternative code which doesn't iterate through map so many times has been added, but commented out (in src/utils commented out, in src/localPRG second function left uncalled)

**Comment by iqbal-lab** [comment]
Cool

**Comment by iqbal-lab** [comment]
Ah - and the alternative code which avoids iterating through maps/sets is actually *slower*

**Comment by rmnorris** [comment]
On the 2 short examples I tried, by a few seconds. The two methods may scale differently with number of prgs/hits though

**Comment by iqbal-lab** [comment]
OK, fine
